development:
 adapter: postgresql
 encoding: utf8
 host: localhost
 database: workshop_development
 pool: 5
 username: postgres
 password: password

test: &TEST
 adapter: postgresql
 encoding: utf8
 host: localhost
 database: workshop_test
 pool: 5
 username: postgres
 password: password

cucumber:
  <<: *TEST